WITH
gen_1 AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
gen_2 AS (
    SELECT a.ID, a.PARENT_ID
    FROM ECOLI_DATA AS a
    INNER JOIN gen_1 AS b ON a.PARENT_ID = b.ID
    
)
SELECT a.ID
FROM ECOLI_DATA AS a
INNER JOIN gen_2 AS b ON a.PARENT_ID = b.ID
ORDER BY ID