-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT ANIMAL_ID, NAME, ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME AS diff_dt
    FROM ANIMAL_OUTS 
    LEFT JOIN ANIMAL_INS USING (ANIMAL_ID, NAME)
    WHERE ANIMAL_INS.ANIMAL_ID IS NOT NULL
) tmp
ORDER BY diff_dt DESC
LIMIT 2