with
A AS (
SELECT *
FROM ANIMAL_INS 
WHERE SEX_UPON_INTAKE LIKE '%Intact%'
)
SELECT ANIMAL_ID, A.ANIMAL_TYPE AS ANIMAL_TYPE , A.NAME AS NAME
FROM A LEFT JOIN ANIMAL_OUTS B USING(ANIMAL_ID)
WHERE B.SEX_UPON_OUTCOME LIKE "%Spayed%" 
OR B.SEX_UPON_OUTCOME LIKE "%Neutered%"