WITH RECURSIVE parents AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT a.ID, a.PARENT_ID, 1 + b.GENERATION AS GENERATION
    FROM ECOLI_DATA AS a
    INNER JOIN parents AS b ON b.ID = a.PARENT_ID
)
SELECT count(a.ID) AS COUNT, GENERATION
FROM parents AS a
LEFT JOIN ECOLI_DATA AS b ON a.ID = b.PARENT_ID
WHERE b.ID IS NULL
GROUP BY GENERATION