-- 코드를 입력하세요
WITH 
A AS (
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS 
),
B AS (
SELECT ANIMAL_ID FROM ANIMAL_OUTS 
)
SELECT NAME, DATETIME
FROM A 
LEFT JOIN B USING(ANIMAL_ID)
WHERE B.ANIMAL_ID IS NULL
ORDER BY DATETIME
LIMIT 3