-- 코드를 입력하세요
WITH
temp AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS="DONE"
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
)
SELECT 
    USER_ID, NICKNAME, TOTAL_SALES
FROM temp
    LEFT JOIN USED_GOODS_USER ON temp.WRITER_ID = USED_GOODS_USER.USER_ID
ORDER BY TOTAL_SALES