-- 코드를 입력하세요
SELECT
    a.TITLE,
    a.BOARD_ID,
    b.REPLY_ID,
    b.WRITER_ID,
    b.CONTENTS,
    DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD a
LEFT JOIN USED_GOODS_REPLY b USING(BOARD_ID)
WHERE TRUE
    AND SUBSTR(a.CREATED_DATE,1,7) = '2022-10'
    AND b.BOARD_ID IS NOT NULL
ORDER BY b.CREATED_DATE, a.TITLE